Tensors 

In [3]:
import numpy as np

In [16]:
# 0-D Tensor (Scalar)
scalar = np.array(7)
print("Scalar (0D):", scalar)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim)

Scalar (0D): 7
Shape: ()
Dimensions: 0


In [ ]:
#1-D Tensor (Vector)
vector = np.array([31,1,2,3])
print("Vector (1D):\n",vector)
print("Shape:", vector.shape)
print("Dimensions:", vector.ndim)

Vector (0D):
 [31  1  2  3]
Shape: (4,)
Dimensions: 1


In [ ]:
#2-D Tensor (Matrix)
matrix = np.array([[31,31],[31,31],[31,31]])
print("Matrix (2D):\n", matrix)
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)

Matrix (0D):
 [[31 31]
 [31 31]
 [31 31]]
Shape: (3, 2)
Dimensions: 2


In [ ]:
#3-D Tensor (Cube like structure) : 2x2x3
tensor3d = np.array([
    [[31,31,31], [31,31,31]],
    [[31,31,31], [31,31,31]]
    ])
print("3D:\n", tensor3d)
print("Shape:", tensor3d.shape)
print("Dimensions:", tensor3d.ndim)

3D:
 [[[31 31 31]
  [31 31 31]]

 [[31 31 31]
  [31 31 31]]]
Shape: (2, 2, 3)
Dimensions: 3


In [30]:
# n-D Tensor (4D example, often used for images: batch, height, width, channels)
tensor4d = np.random.rand(2, 3, 4, 5)  # shape = (2 batches, 3 height, 4 width, 5 channels)
print("4D Tensor shape:", tensor4d.shape)

4D Tensor shape: (2, 3, 4, 5)
